---
version: '3.7'
services:
  ## Eureka Server
  discovery-server:
    image: mthuandkp/discovery-server:v1.0
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ## Product-Service Docker Compose Config
  user-service:
    container_name: user-service
    image: mthuandkp/user-service:v1.0
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server

  api-gateway:
    container_name: api-gateway
    image: mthuandkp/api-gateway:v1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker