import Copyright from '@/components/footer'
import { Box, Container, Typography } from '@mui/material'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Trao đổi tài liệu SGU</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <main className={styles.main}>
				<h1 className="text-3xl font-bold underline">Hello world!</h1>
			</main> */}
			<Container maxWidth="lg">
				<Box
					sx={{
						my: 4,
						display: 'flex',
						flexDirection: 'column',
						justifyContent: 'center',
						alignItems: 'center',
					}}
				>
					<Typography variant="h4" component="h1" gutterBottom color="primary.main">
						MUI v5 + Next.js with TypeScript example
					</Typography>
					<Link href="/client" color="secondary">
						Go to the client page
					</Link>
					<Copyright />
				</Box>
			</Container>
		</>
	)
}
